version: '3'

services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: mkdocs serve -a 0.0.0.0:8000
    restart: unless-stopped
