site_name: AI-Native Programming Paradigm
site_description: Documentation for the AI-Native Programming Paradigm project
repo_url: https://github.com/your-org/ai-native-paradigm
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Contributing: getting-started/contributing.md
  - Roadmap:
    - Overview: roadmap/overview.md
    - Current State: roadmap/current-state.md
    - Target State: roadmap/target-state.md
    - Phase 1: Foundation: roadmap/phase1-foundation.md
    - Phase 2: Core Technology: roadmap/phase2-core.md
    - Phase 3: Development Tooling: roadmap/phase3-tooling.md
    - Phase 4: Integration: roadmap/phase4-integration.md
    - Phase 5: Scaling: roadmap/phase5-scaling.md
    - Phase 6: Ecosystem: roadmap/phase6-ecosystem.md
  # Additional navigation items will be added as documentation grows
